### ISSUE TITLE
What's coming up next for updates?

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#25]
@bell07 What do plan on working on next? Am just wondering :)

**Comment by bell07** [comment]
Today I am consolidating current implementation. Code cleanup and API improvements.
The "Window border" formspec is moved to new method on launcher-app because both are familiar.
The framework supports already a custom launcher. So it is already possible to write own launcher for "historic computer" that seems like before 60 years. With this change it is possible to decorate the apps in the same look.

**Comment by bell07** [comment]
... Starting work on mail app, using https://github.com/cheapie/mail/ for reference

**Comment by bell07** [comment]
.. Started work on support for removable items
See #17, #46

**Comment by bell07** [comment]
I hope the next times I try to get each enhancement in own PR, so no next "Big next updates" should be happen anymore. I prefer the "rolling releases".
My proposal is to assign oneself to the issues working on. If bigger packages needed again, maybe add the "next-release"  Label to the issues.

**Comment by bell07** [comment]
Can we close this issue? I assign issues I working on to me. The development branch exists with incomplete/testing enhancements so you can see what is coming next
